# PyTorch Core Concepts
Welcome to your first hands-on session with **PyTorch** — an open-source deep learning framework built by **Meta**.

In this section, we'll learn:
- What tensors are
- How to create and manipulate them
- How PyTorch enables GPU acceleration


In [1]:
import torch

print("PyTorch version:", torch.__version__)
print("Is CUDA available?", torch.cuda.is_available())


PyTorch version: 2.8.0+cu126
Is CUDA available? True


A **tensor** is a generalization of vectors and matrices to potentially higher dimensions.

In deep learning, tensors are the main data structure used to represent:
- Inputs (e.g. images, text embeddings)
- Model parameters (weights)
- Outputs (predictions)


In [2]:
# Create a tensor from a Python list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

print(x_data)
print("Shape:", x_data.shape)
print("Data type:", x_data.dtype)


tensor([[1, 2],
        [3, 4]])
Shape: torch.Size([2, 2])
Data type: torch.int64


In [4]:
# From a list (manual)
x1 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# From NumPy
import numpy as np
np_array = np.array([[7, 8], [9, 10]])
x2 = torch.from_numpy(np_array)

x1, x2


(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[ 7,  8],
         [ 9, 10]]))

In [5]:
# Random / constant tensors
x3 = torch.rand((2, 3))      # random between 0 and 1
x4 = torch.ones((2, 3))      # all ones
x5 = torch.zeros((2, 3))     # all zeros

x3, x4, x5

(tensor([[0.4819, 0.9026, 0.8474],
         [0.6087, 0.0234, 0.2054]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

We can perform arithmetic and matrix operations directly on tensors.


In [6]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Elementwise multiplication:", a * b)
print("Dot product:", torch.dot(a, b))


Addition: tensor([5, 7, 9])
Subtraction: tensor([-3, -3, -3])
Elementwise multiplication: tensor([ 4, 10, 18])
Dot product: tensor(32)


In [13]:
x = torch.arange(9)          # [0, 1, 2, ..., 8]
x = x.reshape(3, 3)          # reshape into 3x3
print(x)

print("First row:", x[0])
print("Element (2,1):", x[2, 2].item())
print("Element (2,1):", x[1, 2].item())
print("Element (2,1):", x[0, 2].item())

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
First row: tensor([0, 1, 2])
Element (2,1): 8
Element (2,1): 5
Element (2,1): 2


PyTorch makes GPU acceleration simple — just move your tensor or model to a CUDA device.


In [8]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x_gpu = x.to(device)
    print("Tensor moved to:", x_gpu.device)
else:
    print("CUDA not available. Running on CPU.")


Tensor moved to: cuda:0


One of PyTorch’s superpowers is **automatic differentiation**.

When we set `requires_grad=True`, PyTorch tracks operations on that tensor so we can compute gradients automatically during training.


In [15]:
# Create tensor with gradient tracking
x = torch.tensor([2.0, 3.0], requires_grad=True)

# Simple computation
y = x ** 2 + 3 * x

# Compute gradients (dy/dx)
y.sum().backward()
print("Gradients:", x.grad)


Gradients: tensor([7., 9.])


In this section, you learned:
- How to create and manipulate tensors
- Perform operations and reshaping
- Move tensors between CPU and GPU
- Enable gradient tracking with `requires_grad=True`

Next: We'll use these concepts to build **neural networks in PyTorch**.
